---
title: Your awesome title
timezone: UTC
collections:
  photo_gallery:
    title: Photo Gallery
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl:
url:
twitter_username: jekyllrb
<<<<<<< HEAD
github_username:  jekyll
collections:
  - photo_gallery
defaults:
  -
    scope:
      path: ""
      type: "photo_gallery"
    values:
      image_path: ""

# Build settings
=======
github_username: jekyll
>>>>>>> 741199f36a61696faa5c0a52cb8d5d2614c6878a
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
